mindmap
    root((ecommerce-platform))
        Stack
            Rust
            SQLx
            Docker
        Entities
            Product) ) (CreateProduct) ) (Order) ) (OrderItemRequest) ) (PlaceOrder