mindmap
    root((library-management))
        Stack
            Rust
            SQLx
            Docker
        Entities
            Book) ) (CreateBook) ) (Member) ) (CreateMember) ) (Loan) ) (LoanRequest