mindmap
    root((restaurant-res))
        Stack
            Rust
            SQLx
            Docker
        Entities
            RestaurantTable) ) (CreateTableRow) ) (Reservation) ) (CreateReservation