mindmap
    root((finance-manager))
        Stack
            Rust
            SQLx
            Docker
        Entities
            Account) ) (CreateAccount) ) (TransactionRecord) ) (CreateTransaction