CREATE TABLE stocks (
    id SERIAL PRIMARY KEY,
    symbol TEXT UNIQUE NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    change_percent DOUBLE PRECISION NOT NULL,
    last_updated TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
