mindmap
    root((currency-converter))
        Stack
            Rust
            SQLx
            Docker
        Entities
            ExchangeRate) ) (CreateExchangeRate) ) (Conversion) ) (PerformConversion